# Generated by Django 4.1.3 on 2022-12-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('prd_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
