# Generated by Django 4.1.3 on 2022-12-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proKApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
