# Generated by Django 4.1.3 on 2022-12-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proKApp', '0002_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('description', models.TextField()),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('OR', 'Ornamental'), ('FR', 'Furniture'), ('AR', 'Accessories')], max_length=2)),
                ('prodcut_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
