# Generated by Django 4.1.3 on 2022-12-20 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proKApp', '0006_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
    ]
